# Generated by Django 3.2.4 on 2021-06-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('Correo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Correo')),
                ('Contraseña1', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('Contraseña2', models.CharField(max_length=50, verbose_name='Repita Contraseña')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
